### ISSUE TITLE
Could not resolve dependencies: Could not find artifact org.kordamp.maven:pomchecker:jar:1.8.0 in mavencentral

### ISSUE THREAD

**Issue by helpermethod** [kordamp/jbang-catalog#1]
So I gave the `pomchecker` a try as described in the README.md and this happens

```
$ jbang pomchecker@kordamp
[jbang] Resolving dependencies...
[jbang]    org.kordamp.maven:pomchecker:1.8.0
[jbang] [ERROR] Could not resolve dependencies: Could not find artifact org.kordamp.maven:pomchecker:jar:1.8.0 in mavencentral (https://repo1.maven.org/maven2/)
[jbang] Run with --verbose for more details
```

**Comment by aalmiray** [comment]
Indeed. Looks like the JAR is missing https://repo1.maven.org/maven2/org/kordamp/maven/pomchecker/1.8.0/

**Correction:** the jbang script points to the wrong artifact, it should be `pomchecker-cli`.

**Comment by aalmiray** [comment]
Pomchecker `1.9.0` was just released. It should have fixed this problem 😅
